import { useEffect, useState } from "react";
import { Link } from "wouter";
import { subscribeToSettings } from "@/lib/firestore-ops";
import { PartnerInquiryForm } from "@/components/InterestForms";
import type { FirestoreSettings } from "@shared/firestore-schemas";

export default function Partnerships() {
  const [settings, setSettings] = useState<FirestoreSettings>({ orphans: 0, students: 0, patients: 0, families: 0 });
  useEffect(() => subscribeToSettings(setSettings), []);
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <section className="bg-gradient-to-bl from-[#123c2c] via-[#18563d] to-emerald-700 px-4 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-[0.16em] text-emerald-100">شراكات تصنع أثراً مسؤولاً</p><h1 className="mt-3 max-w-4xl text-4xl font-black leading-tight md:text-6xl">{settings.partnershipsHeadline || "نتعاون لنحوّل الموارد إلى أثر يمكن تتبعه"}</h1><p className="mt-6 max-w-3xl whitespace-pre-line text-lg leading-8 text-emerald-50">{settings.partnershipsDescription || "ندعو الشركات والجهات المانحة والمؤسسات الشريكة إلى دعم برامج واضحة، بمؤشرات أثر ومحتوى موثق وقنوات تواصل مباشرة."}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#partner-inquiry" className="rounded-xl bg-white px-5 py-3 font-bold text-[#123c2c]">ابدأوا طلب شراكة</a><Link href="/transparency" className="rounded-xl border border-white/40 px-5 py-3 font-bold text-white hover:bg-white/10">مركز الشفافية</Link></div></div></section>
      <main className="mx-auto max-w-6xl space-y-14 px-4 py-16">
        <section><div className="max-w-3xl"><p className="font-bold text-emerald-700">لماذا الشراكة معنا؟</p><h2 className="mt-3 text-3xl font-black md:text-4xl">ملف مؤسسي منظم بدلاً من وعود عامة</h2><p className="mt-4 whitespace-pre-line leading-8 text-slate-600">{settings.partnershipsWhy || "نجهز المعلومات والوثائق التي تساعد جهة التمويل في فهم البرنامج المقترح، والفئات المستفيدة، وآلية المتابعة، والنتائج التي يمكن قياسها. لا ننشر أرقاماً أو شهادات غير موثقة."}</p></div><div className="mt-8 grid gap-5 md:grid-cols-3"><article className="rounded-2xl border border-emerald-100 bg-emerald-50 p-6"><h3 className="font-black">برامج قابلة للتخصيص</h3><p className="mt-2 whitespace-pre-line leading-7 text-slate-600">{settings.partnershipsPrograms || "يمكن مواءمة التعاون مع التعليم والصحة وسقيا المياه والإغاثة والتمكين وفق نطاق وموازنة متفق عليهما."}</p></article><article className="rounded-2xl border border-emerald-100 bg-emerald-50 p-6"><h3 className="font-black">مؤشرات أثر</h3><p className="mt-2 whitespace-pre-line leading-7 text-slate-600">{settings.partnershipsImpact || "تُربط الأنشطة بمؤشرات زمنية ومصادر بيانات، ثم تقدم التحديثات في تقارير يحددها اتفاق الشراكة."}</p></article><article className="rounded-2xl border border-emerald-100 bg-emerald-50 p-6"><h3 className="font-black">إعلام مسؤول</h3><p className="mt-2 whitespace-pre-line leading-7 text-slate-600">{settings.partnershipsMedia || "توثق مكتبة الوسائط كل مادة بسياقها وحقوقها وموافقة النشر قبل مشاركتها علناً."}</p></article></div></section>
        <section className="grid gap-8 rounded-3xl bg-slate-950 p-8 text-white md:grid-cols-2"><div><p className="font-bold text-emerald-300">ماذا يمكننا تقديمه عند بدء التقييم؟</p><h2 className="mt-3 text-3xl font-black">حزمة عناية واجبة تُستكمل بالوثائق المعتمدة</h2></div><div className="whitespace-pre-line leading-8 text-slate-200">{settings.partnershipsDueDiligence || "تعريف قانوني ورسالة المؤسسة وبرامجها.\nقائمة مجلس الأمناء والمسؤولين عند اعتمادها للنشر.\nتقارير وملخصات مالية ووثائق تسجيل بحسب ما تسمح به المؤسسة.\nنطاق برنامج، ميزانية، مؤشرات أثر، وخطة متابعة للمشروع المقترح."}</div></section>
        <section className="grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><p className="text-sm font-bold tracking-[0.14em] text-emerald-700">ملخص بالعربية</p><h2 className="mt-2 text-2xl font-black">موجز شراكة قابل للمراجعة</h2><p className="mt-3 leading-7 text-slate-600">يعرض مراحل التقييم ونطاق المعلومات التي يمكن تنظيمها وحدود ما لا يمثله الموجز قبل الاتفاق.</p><Link href="/partner-brief" className="mt-5 inline-block rounded-xl border border-emerald-700 px-4 py-2.5 font-bold text-emerald-800 hover:bg-emerald-50">عرض الموجز العربي</Link></article><article className="rounded-3xl border border-slate-200 bg-slate-50 p-7"><p className="text-sm font-bold tracking-[0.14em] text-emerald-700">للجهات الدولية</p><h2 className="mt-2 text-2xl font-black">ملخص إنجليزي مبدئي للشراكة</h2><p className="mt-3 leading-7 text-slate-600">صفحة تعريفية مختصرة توضح مسار التعاون وحدود المعلومات العامة قبل مشاركة أي وثائق أو تفاصيل تخضع للموافقة.</p><Link href="/international-brief" className="mt-5 inline-block rounded-xl border border-emerald-700 px-4 py-2.5 font-bold text-emerald-800 hover:bg-emerald-50">Open English partner brief</Link></article></section>
        <PartnerInquiryForm />
      </main>
    </div>
  );
}
